name: Docker Image wm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tag/}" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tino/wbms_fe
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag the Docker image
        run: docker tag wbms_fe almyra/wbms_fe:latest
      - name: Push to DockerHub
        run: docker push almyra/wbms_fe:latest
      - name: Tag the Docker image
        run: docker tag tino/wbms_fe almyra/wbms_fe:$(date +'%Y-%m-%d')
      - name: Push the tagged Docker image
        run: docker push almyra/wbms_fe:$(date +'%Y-%m-%d')
